language: android
jdk: oraclejdk11
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-33"
  - yes | sdkmanager "build-tools;30.0.3"
