sudo: required
language: android
jdk: oraclejdk8
dist: trusty
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-33
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"
